https://g.dev/kareem-jadou0653] Gen204 (133327711) | https://www.google.ru/generate_204 | 204 0258] Gen204 (133327711) | http://clients1.google.com/generate_204 | 20 0002] ConnectionService (60794121) |Broadcast Broadcast | CONNECTED

99s] Default network: Wi-Fi

0015] Default network: Mobile

-[cut here]

99s] NetworkReceiver (227487736) [dynamic] | Intent:
